# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dgarana Blog
author: David Garaña
email: david@dgarana.com
description: My personal blog hosted at github.io!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dgarana.github.io" # the base hostname & protocol for your site
twitter_username: davidgarana
github_username:  dgarana
linkedin_username: dgarana

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
